// <auto-generated />
namespace DealDouble.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addParentCategoryDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addParentCategoryDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "202003181430110_addParentCategoryDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
